### ISSUE TITLE
Suggestion: Push and run in another server

### ISSUE THREAD

**Issue by alur222** [engagespark/pushabutton#24]
First of all, nice project I am forking it soon! :)

Would it be possible if this could support running commands on a different server? Like pushabutton-server runs a script in production-server?

BTw, I have a similar project written nodejs/meteorjs. But the dynamic button didn't land into my mind before I discovered this.

Awesome!!! <3 :beers:

**Comment by mknecht** [comment]
Cheers Raul :) Re your question: In a sense, that's possible already, because you can just put a bash script with an SSH command:

```
#!/bin/bash
ssh your-server ls
``` 

If you mean to select a server and then run the script there: Sure, can be built, but extends the notion of “just exposing what's there already in a simple way”. Let me think about that…

**Comment by alur222** [comment]
oh yeah hahaha I was using username/password. I didn't realize I can just copy the server's public id to the production server. Nice Thanks!
